export const LOAD_CURRENT_FLOW = 'LOAD_CURRENT_FLOW';
export const CURRENT_FLOW_FAIL = 'CURRENT_FLOW_FAIL';
export const RESET_CURRENT_FLOW = 'RESET_CURRENT_FLOW';

export const LOAD_APP_STATE = 'LOAD_APP_STATE';
export const APP_STATE_FAIL = 'APP_STATE_FAIL';
export const RESET_APP_STATE = 'RESET_APP_STATE';
export const UPDATE_APP_STATE = 'UPDATE_APP_STATE';